//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCart2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_details
    {
        public int did { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> pprice { get; set; }
        public Nullable<int> pqty { get; set; }
        public Nullable<int> pamount { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
