//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCart2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_orders()
        {
            this.tbl_order_details = new HashSet<tbl_order_details>();
        }
    
        public int oid { get; set; }
        public byte[] odate { get; set; }
        public string opname { get; set; }
        public string opphone { get; set; }
        public string opaddress { get; set; }
        public string opsaddress { get; set; }
        public string oamount { get; set; }
        public Nullable<int> ostatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_details> tbl_order_details { get; set; }
    }
}
